// This file is auto-generated by scripts/generate-memories.js
// Do not edit manually if you plan to run the script again.

export const generatedMemories = [
  {
    "id": 0,
    "image": "/memories/photo1.png",
    "caption": "A beautiful memory",
    "date": "2025"
  },
  {
    "id": 1,
    "image": "/memories/photo10.png",
    "caption": "A beautiful memory",
    "date": "2025"
  },
  {
    "id": 2,
    "image": "/memories/photo11.png",
    "caption": "A beautiful memory",
    "date": "2025"
  },
  {
    "id": 3,
    "image": "/memories/photo12.png",
    "caption": "A beautiful memory",
    "date": "2025"
  },
  {
    "id": 4,
    "image": "/memories/photo2.png",
    "caption": "A beautiful memory",
    "date": "2025"
  },
  {
    "id": 5,
    "image": "/memories/photo3.png",
    "caption": "A beautiful memory",
    "date": "2025"
  },
  {
    "id": 6,
    "image": "/memories/photo4.png",
    "caption": "A beautiful memory",
    "date": "2025"
  },
  {
    "id": 7,
    "image": "/memories/photo5.png",
    "caption": "A beautiful memory",
    "date": "2025"
  },
  {
    "id": 8,
    "image": "/memories/photo6.png",
    "caption": "A beautiful memory",
    "date": "2025"
  },
  {
    "id": 9,
    "image": "/memories/photo7.png",
    "caption": "A beautiful memory",
    "date": "2025"
  },
  {
    "id": 10,
    "image": "/memories/photo8.png",
    "caption": "A beautiful memory",
    "date": "2025"
  },
  {
    "id": 11,
    "image": "/memories/photo9.png",
    "caption": "A beautiful memory",
    "date": "2025"
  }
];
